#!/bin/bash
# Script to install FreeFEM++ with OpenBLAS
# Written by Ghanghoon "Will" Paik (gip5038@psu.edu)
# Feb 19 2019

# size: ~1.6 GB

module load gcc/5.3.1
module load openmpi
module load petsc
module load blas
module load lapack

BASE=$PWD

mkdir freefem
BUILD_DIR=$BASE/freefem

# Install OpenBLAS
git clone https://github.com/xianyi/OpenBLAS.git
cd OpenBLAS
make
make PREFIX=$BUILD_DIR install

cd $BASE

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BUILD_DIR/lib

# Install FreeFEM++
git clone https://github.com/FreeFem/FreeFem-sources.git
cd FreeFem-sources
tar zxvf AutoGeneratedFile.tar.gz
./configure --enable-download --enable-optim --disable-pastix --prefix=$BUILD_DIR

./download/getall -a

cd download/ff-petsc
make petsc-slepc

cd $BASE/FreeFem-sources

./reconfigure

make
make install

# Delete source files
cd $BASE
rm -rf OpenBLAS FreeFem-sources
