#!/bin/bash
# Script to install FreeFEM++ with OpenBLAS
# Written by Ghanghoon "Will" Paik (gip5038@psu.edu)
# Feb 19 2019

# size: ~1.6 GB

source /opt/rh/devtoolset-8/enable

BASE=/opt/sw/

mkdir -p $BASE/freefem
BUILD_DIR=$BASE/freefem

cd $BASE

# Install FreeFEM++
git clone https://github.com/FreeFem/FreeFem-sources.git
cd FreeFem-sources
tar zxvf AutoGeneratedFile.tar.gz
./configure --enable-download --enable-optim --disable-pastix --prefix=$BUILD_DIR

./download/getall -a

cd download/ff-petsc
make petsc-slepc

cd $BASE/FreeFem-sources

./reconfigure

make
make install

# Delete source files
cd $BASE
rm -rf FreeFem-sources
